<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Nima Table2</title>
</head>
<body>

  <!-- 
    Nima Memarzadeh
    Bellevue University
    Assignment: Table2
    Description: 
      This program demonstrates how to use nested PHP loops 
      to create a two-dimensional HTML table.
      Each cell displays a random number from 1 to 6.
      Note: The HTML table tags are NOT generated by PHP; 
      PHP is only used for the table content.
  -->

  <h2>Random Numbers Table</h2>

  <table border="1" width="400">
    <caption>Two Dimensional Table of Random Numbers</caption>
    <thead>
      <tr>
        <td colspan="8" style="text-align:center;">Numbers 1 - 6</td>
      </tr>
    </thead>
    <tbody>
      <?php 
        // Outer loop controls the rows
        for ($row = 0; $row < 8; $row++) { 
      ?>
        <tr>
          <?php 
            // Inner loop controls the columns (cells in each row)
            for ($col = 0; $col < 8; $col++) { 
          ?>
            <td>
              <?php 
                // Display a random number between 1 and 6
                echo rand(1, 6); 
              ?>
            </td>
          <?php 
            } // end inner loop 
          ?>
        </tr>
      <?php 
        } // end outer loop 
      ?>
    </tbody>
  </table>

</body>
</html>
